# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build and test
on: [pull_request, push]
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: build
    runs-on: self-hosted
    strategy:
      matrix:
        # Use these Java versions
        java: [ 17, ]  # Current Java LTS & minimum supported by Minecraft
    steps:
      - name: checkout vereya
        uses: actions/checkout@v3
        with:
          repository: trueagi-io/Vereya
          path: Vereya
      - name: install vereya
        run: rm /home/tester/.minecraft/mods/* && cp $GITHUB_WORKSPACE/Vereya/jars/* /home/tester/.minecraft/mods/
      - name: install fabric
        run: rsync -v $GITHUB_WORKSPACE/Vereya/fabric/* /home/tester/.minecraft/mods/
      - name: checkout tagilmo
        uses: actions/checkout@v3
        with:
          repository: trueagi-io/minecraft-demo
          path: $GITHUB_WORKSPACE
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: start minecraft
        working-directory: ./Vereya
        run: ./launch.sh &
        env:
          DISPLAY: :99
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
      - name: install tagilmo
        run: conda activate py31 && pip install .
      - name: run test
        run: |
          ps a|grep [j]ava &&
          conda activate py31 && cd $GITHUB_WORKSPACE/tests/vereya &&
          python run_tests.py
